version: '3.9'

services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - ./database:/var/lib/mysql
  gallery:
    build:
      context: backend/gallery
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./uploaded:/uploaded
    depends_on:
      database:
        condition: service_started
  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      families:
        condition: service_healthy
  species:
    build:
      context: backend/species
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck: &healthcheck
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s
    volumes:
      - ./sentfiles:/sentfiles

  families:
    build:
      context: backend/family
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      <<: *healthcheck
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
    depends_on:
      species:
        condition: service_healthy
  reverse_proxy:
    build:
      context: .
      dockerfile: ./reverse_proxy/Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      gateway:
        condition: service_started
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env
