version: '3.9'

services:
  database:
    image: mariadb
    container_name: database
    environment:
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - ./database:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./uploaded:/uploaded
    depends_on:
      - database
    environment:
      - BACKEND_PORT=8083
  backend2:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./uploaded:/uploaded
    depends_on:
      - database
    environment:
      - BACKEND_PORT=8084
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_PORT=2137
    ports:
      - "2137:2137"
  frontend2:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_PORT=2138
    ports:
      - "2138:2138"
  load_balancer:
    build:
      context: load_balancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
  internal_load_balancer:
    build:
      context: internal_load_balancer
      dockerfile: Dockerfile
    ports:
      - "420:420"
